---
- name: "Set up version of mongo to install"
  copy:
    src="{{ database_repo_src }}" 
    dest="{{ database_repo_dest }}"
    
- name: "Install mongodb"
  package:
    name: "mongodb-org"
    state: installed
  notify: preload database

- name: "Ensure mongod is enabled and started"
  systemd:
    name: mongod
    enabled: true
    daemon_reload: true
    state: restarted
...